### PR TITLE
Accept without personal number

### PR DESCRIPTION
**Pull request by jongotlin**
### Description
Passing personal number is optional.

### Checklist
- [x] Code compiles correctly
- [x] Code conforms PSR-2. Recommending use PHP CS Fixer with next rules: `--rules=@PSR2,blank_line_before_return,no_unused_imports`
- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing
- [x] Extended the README, if necessary
- [ ] Added myself / the copyright holder to the authors in composer.json file

### CODE REVIEW

**Comment by jongotlin** [comment]
I don't think passing real requests in tests will work.

**Comment by lurifuchs** [comment]
What's the status for this PR? I would like to see this merge, solution looks good.

**Review by lurifuchs — APPROVED** [review]
Looks like a good solution.

**Comment by jongotlin** [comment]
Thanks for merging. Can you please tag a release on Packagist? `dev-dev` is not pointing to the latest commit.

**Pull request merged**
